os:
  - linux
  - osx

language: c
sudo: no

compiler:
  - gcc
cache: ccache

script:
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir build
  - cd build
  - ../configure CC="ccache gcc"
  - make -j4
  - make install

notificastions:
  email:
    recipients:
      - releng@pivotal.io
    on_success: change
    on_failure: always
